package com.example.task1.mybatis.model;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.NAME
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.SALARY
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    private Double salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.COMPANY_ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.ID
     *
     * @return the value of PUBLIC.PERSON.ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.ID
     *
     * @param id the value for PUBLIC.PERSON.ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.NAME
     *
     * @return the value of PUBLIC.PERSON.NAME
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.NAME
     *
     * @param name the value for PUBLIC.PERSON.NAME
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.SALARY
     *
     * @return the value of PUBLIC.PERSON.SALARY
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.SALARY
     *
     * @param salary the value for PUBLIC.PERSON.SALARY
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.COMPANY_ID
     *
     * @return the value of PUBLIC.PERSON.COMPANY_ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.PERSON.COMPANY_ID
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}