package com.example.task1.mybatis.dao;

import com.example.task1.mybatis.model.Person;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Fri Mar 25 14:24:31 EET 2022
     */
    int updateByPrimaryKey(Person record);
}